# This is a minimal chaparral configuration.

# server listen port
listen: ":8080"

# Storage Backend 
#
# The backend can be set here or using the CHAPARRAL_BACKEND environment
# variable. If it's set in both places, the environment variable value
# is used.
#
# S3 example
# backend: s3://ocfl-bucket?region=us-west-2

# Default value uses wokring directory of the local filesystem
# backend: file://.


# Upload path
#
# Set 'uploads' to a directory path (relative to the backend) where uploads will
# be stored. Note that storage root paths must not include or be included in
# this directory. The default value ("") disables uploads.
uploads: "uploads"

# Sorage Root config
#
# Multiple OCFL storage roots can be configured. Here the default storage root
# path is set to `ocfl-default` (relative to the backend). If the storage root
# doesn't exist, it will be created using values in `init`. Additional storage
# roots can be added, but they need to include a unique, non-empty `id` value.
roots:
- id: "main"
  path: "ocfl-default" # path relative to CHAPARRAL_BACKEND
  init:
    # if the storage doesn't exist it will be created with 
    # these optiosn
    description: "default storage root"
    layout: "0003-hash-and-id-n-tuple-storage-layout"


# Permissions config
#
# The permissions block defines a roles in terms of actions they can perform
# for a set of resources (i.e., OCFL objects). You may use whatever naming
# convention you like for the roles names, however actions and resources  should
# follow a set form. Allowed actions are `read_object`, `commit_object`,
# `delete_object`, and `*`. The latter matches any action. Resources should  have
# the form `root-id::object-id`, where root-id is the ID set in the Storage
# Root Config and object-id is the ocfl object ID. `root-id::*` matches any object
# in the storage root with given id; `*::*` matches any object regardless of its
# storage root.
#
# The "default" permission can be used base permissions for all users, including
# un-authenticated requests.
permissions:
  default: {} # no access by default
  roles:
    # members can read any object in the 'main' storage root
    chaparral_member:
      read_object: ["main::*"]

    # admins can do any action to any resource
    chaparral_admin: 
      "*": ["*::*"]
