// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlite

import (
	"time"
)

type Upload struct {
	ID         string
	Size       int64
	UploaderID string
	Digests    []byte
}

type Uploader struct {
	ID          string
	RootID      string
	UserID      string
	Algs        string
	Description string
	CreatedAt   time.Time
}
